kind: Schedule
apiVersion: chaos-mesh.org/v1alpha1
metadata:
  namespace: mssql
  name: mssql-exporter-stress
  annotations:
    experiment.chaos-mesh.org/pause: 'false'
spec:
  schedule: '*/3 * * * *'
  startingDeadlineSeconds: null
  concurrencyPolicy: Allow
  historyLimit: 1
  type: StressChaos
  stressChaos:
    selector:
      namespaces:
        - mssql
      labelSelectors:
        'pod_type': 'exporter'
    mode: all
    stressors:
      memory:
        workers: 1
        size: 50%
      cpu:
        workers: 1
        load: 40
    duration: 20s
