kind: Schedule
apiVersion: chaos-mesh.org/v1alpha1
metadata:
  namespace: sql-exporter
  name: sql-exporter-stress
  annotations:
    experiment.chaos-mesh.org/pause: 'false'
spec:
  schedule: '*/3 * * * *'
  startingDeadlineSeconds: 5
  concurrencyPolicy: Allow
  historyLimit: 1
  type: StressChaos
  stressChaos:
    selector:
      namespaces:
        - sql-exporter
      labelSelectors:
        'pod_type': 'exporter'
    mode: all
    stressors:
      memory:
        workers: 2
        size: 25%
      cpu:
        workers: 2
        load: 25
    duration: 20s
