apiVersion: v1
kind: ConfigMap
metadata:
  name: mysql-sql-config
  namespace: sql-exporter
data:
  mysql.collector.yml: |-
    collector_name: mysql_standard
    metrics:
      - metric_name: mysql_uptime
        type: gauge
        help: 'MySQL server uptime in seconds.'
        key_labels: []
        values: [Value]
        query: |
          SHOW STATUS LIKE 'Uptime'

      - metric_name: mysql_connections
        type: gauge
        help: 'Number of client connections to the MySQL server.'
        key_labels:
          - type
        values: [value]
        query: |
          SELECT 'total' AS type, COUNT(*) AS value FROM information_schema.processlist
          UNION ALL
          SELECT 'idle', COUNT(*) FROM information_schema.processlist WHERE Command='Sleep'
          UNION ALL
          SELECT 'active', COUNT(*) FROM information_schema.processlist WHERE Command!='Sleep'

      - metric_name: mysql_qps
        type: counter
        help: 'Number of queries per second.'
        values: [Value]
        query: |
          SHOW GLOBAL STATUS LIKE 'Queries'

      - metric_name: mysql_slow_queries
        type: counter
        help: 'Number of slow queries processed by the MySQL server.'
        values: [Value]
        query: |
          SHOW GLOBAL STATUS LIKE 'Slow_queries'
