apiVersion: v1
kind: ConfigMap
metadata:
  name: oracle-sql-config
  namespace: sql-exporter
data:
  oracle_config.yaml: |-
    global:
      scrape_timeout_offset: 500ms
      min_interval: 0s
      max_connections: 3
      max_idle_connections: 3
      max_connection_lifetime: 5m

    target:
      data_source_name: 'oracle://system:Weops123!@db21c-oracle-db.oracle:1521/ORCLCDB'
      collectors: [oracle_*]

    collector_files:
      - "oracle.collector.yaml"


  oracle.collector.yaml: |-
    collector_name: oracle_standard
    metrics:
      - metric_name: oracle_version
        type: gauge
        help: 'Oracle database version information.'
        key_labels:
          - VERSION
        values: [VALUE]
        query: |
          SELECT version AS version, 1 AS value FROM v$instance

      - metric_name: oracle_uptime
        type: gauge
        help: 'Oracle database uptime in seconds.'
        key_labels: []
        values: [VALUE]
        query: |
          SELECT (SYSDATE - STARTUP_TIME) * 86400 AS VALUE FROM v$instance
